# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "JIHYUN'S BLOG"
description:         '배운 내용들을 정리하는 공간'
url:                 http://jihyun00.github.io
baseurl:             'http://jihyun00.github.io'
paginate:            5

# About/contact
author:
  name:              Jihyun Choi 
  url:               https://facebook.com/ahsa17
  email:             noblea1117@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
